name: Deploy Scraper Service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SUPERSTACK_SERVICE_TOKEN:
        required: true
      PIP_INDEX_URL:
        required: true
      KUBE_CONFIG_STAGING:
        required: true
      JF_ARTIFACTORY_SECRET_1:
        required: true
      SUPERSTACK_DOCKER_REGISTRY:
        required: true

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Service
        uses: actions/checkout@v2
        with:
          repository: superstack-dev/superstack-runner
          ref: staging
          token: ${{ secrets.SUPERSTACK_SERVICE_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "scraper/package"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build and tag image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/scraper
          file: ${{ github.workspace }}/Dockerfile
          push: false
          tags: ${{ secrets.SUPERSTACK_DOCKER_REGISTRY }}/${{ inputs.service_name }}-staging:${{ github.sha }},${{ secrets.SUPERSTACK_DOCKER_REGISTRY }}/${{ inputs.service_name }}-staging:latest
          build-args: |
            PIP_INDEX_URL=${{ secrets.PIP_INDEX_URL }}
            PIP_ARGS=--pre

      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}

      - env:
          SUPERSTACK_DOCKER_REGISTRY: ${{ secrets.SUPERSTACK_DOCKER_REGISTRY }}
          IMAGE_NAME: ${{ inputs.service_name }}-staging
          IMAGE_TAG: ${{ github.sha }}
        run: |
          jfrog rt dp $SUPERSTACK_DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG superstack-docker
          jfrog rt dp $SUPERSTACK_DOCKER_REGISTRY/$IMAGE_NAME:latest superstack-docker

      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_STAGING }}
          DP_NAME: ${{ inputs.service_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: rollout restart deployment/$DP_NAME

      - name: verify deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_STAGING }}
          DP_NAME: ${{ inputs.service_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: rollout status deployment/$DP_NAME
