name: Deploy Service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      KUBE_CONFIG:
        required: true
      JF_ARTIFACTORY_SECRET:
        required: true
      SUPERSTACK_DOCKER_REGISTRY:
        required: true

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: production
    env:
      IMAGE_NAME: ${{ inputs.service_name }}-prod
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JFrog
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET }}

      - name: Pull Builder Image
        env: 
          SUPERSTACK_DOCKER_REGISTRY: ${{ secrets.SUPERSTACK_DOCKER_REGISTRY }}
        run: jfrog rt docker-pull $SUPERSTACK_DOCKER_REGISTRY/service-runner-prod:latest superstack-docker

      - name: Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: '.'
          builder_image: ${{ secrets.SUPERSTACK_DOCKER_REGISTRY }}/service-runner-prod:latest
          image: ${{ secrets.SUPERSTACK_DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          log_level: 5
          tags: ${{ env.IMAGE_TAG }} latest

      - name: Push Image
        env:
          SUPERSTACK_DOCKER_REGISTRY: ${{ secrets.SUPERSTACK_DOCKER_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: jfrog rt dp $SUPERSTACK_DOCKER_REGISTRY/$IMAGE_NAME:latest superstack-docker

      - name: Deploy To Cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          DP_NAME: ${{ inputs.service_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: rollout restart deployment/$DP_NAME

      - name: Verify Deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          DP_NAME: ${{ inputs.service_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: rollout status deployment/$DP_NAME
