name: Python Tests

on:
  workflow_call:
    secrets:
      PIP_INDEX_URL:
        required: true

jobs:
  test:
    name: Test Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Pytest
        run: pip install -U pytest

      - name: Install Dependencies
        env:
          PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}
        run: |
          pip install -r requirements.txt
          [ -f test-requirements.txt ] && pip xsinstall -r test-requirements.txt || true

      - name: Run Tests
        if: hashFiles('tests/__init__.py') != ''
        run: python -m pytest tests/
